### ISSUE TITLE
Fichier manquant

### ISSUE THREAD

**Issue by MarieEtienne** [AgrocampusDS/visualisation-birds#1]
Le fichier AllSpeciesBirdLifeMaps2019.csv n'est pas dans le répertoire data.

**Comment by MarionMoussay** [comment]
On n'a pas réussit à le mettre car il est trop gros et un message d'erreur s'affiche lorsque l'on veut le push

**Comment by MarieEtienne** [comment]
J'ai géré avec le fichier compressé en le décompressant dans le code directement grace au package archive
