### ISSUE TITLE
Packages nécessaires

### ISSUE THREAD

**Issue by MarionMoussay** [AgrocampusDS/visualisation-birds#2]
Nous avons besoin des packages suivants : phytools, readxl, rgdal, rgeos, sf, RColorBrewer, ggplot2, dplyr, ggExtra, grid, gridExtra, tidyverse, extrafont, plotly, ggridges, showtext

**Comment by MarieEtienne** [comment]
J'ai installé les packages et normalement réussi à faire fonctionner votre dashoard. Le fichier compressé a compliqué un peu l'affaire mais ca doit etre bon maintenant
